//
//  EInputKey.h
//  Input Key Codes.
//
//  Created by Kirill Bravichev on 03/10/2021.
//  Copyright (c) 2021 Cellyceos. All rights reserved.
//

#pragma once

#ifdef USE_SDL
#include "SDL_keycode.h"

enum class EInputKey
{
    Unknown = SDLK_UNKNOWN,

    Return = SDLK_RETURN,
    Escape = SDLK_ESCAPE,
    Backspace = SDLK_BACKSPACE,
    Tab = SDLK_TAB,
    Space = SDLK_SPACE,
    Exclaim = SDLK_EXCLAIM,
    DoubleQuotes = SDLK_QUOTEDBL,
    Hash = SDLK_HASH,
    Percent = SDLK_PERCENT,
    Dollar = SDLK_DOLLAR,
    Ampersand = SDLK_AMPERSAND,
    SingleQuote = SDLK_QUOTE,
    LeftParenthesis = SDLK_LEFTPAREN,
    RightParenthesis = SDLK_RIGHTPAREN,
    Asterisk = SDLK_ASTERISK,
    Plus = SDLK_PLUS,
    Comma = SDLK_COMMA,
    Minus = SDLK_MINUS,
    Period = SDLK_PERIOD,
    Slash = SDLK_SLASH,
    Num0 = SDLK_0,
    Num1 = SDLK_1,
    Num2 = SDLK_2,
    Num3 = SDLK_3,
    Num4 = SDLK_4,
    Num5 = SDLK_5,
    Num6 = SDLK_6,
    Num7 = SDLK_7,
    Num8 = SDLK_8,
    Num9 = SDLK_9,
    Colon = SDLK_COLON,
    Semicolon = SDLK_SEMICOLON,
    Less = SDLK_LESS,
    Equal = SDLK_EQUALS,
    Greater = SDLK_GREATER,
    Question = SDLK_QUESTION,
    At = SDLK_AT,

    /*
       Skip uppercase letters
     */
    LeftBracket = SDLK_LEFTBRACKET,
    BackSlash = SDLK_BACKSLASH,
    RightBracket = SDLK_RIGHTBRACKET,
    Caret = SDLK_CARET,
    Underscore = SDLK_UNDERSCORE,
    Backquote = SDLK_BACKQUOTE,
    A = SDLK_a,
    B = SDLK_b,
    C = SDLK_c,
    D = SDLK_d,
    E = SDLK_e,
    F = SDLK_f,
    G = SDLK_g,
    H = SDLK_h,
    I = SDLK_i,
    J = SDLK_j,
    K = SDLK_k,
    L = SDLK_l,
    M = SDLK_m,
    N = SDLK_n,
    O = SDLK_o,
    P = SDLK_p,
    Q = SDLK_q,
    R = SDLK_r,
    S = SDLK_s,
    T = SDLK_t,
    U = SDLK_u,
    V = SDLK_v,
    W = SDLK_w,
    X = SDLK_x,
    Y = SDLK_y,
    Z = SDLK_z,

    CapsLock = SDLK_CAPSLOCK,

    F1 = SDLK_F1,
    F2 = SDLK_F2,
    F3 = SDLK_F3,
    F4 = SDLK_F4,
    F5 = SDLK_F5,
    F6 = SDLK_F6,
    F7 = SDLK_F7,
    F8 = SDLK_F8,
    F9 = SDLK_F9,
    F10 = SDLK_F10,
    F11 = SDLK_F11,
    F12 = SDLK_F12,

    PrintScreen = SDLK_PRINTSCREEN,
    ScrollLock = SDLK_SCROLLLOCK,
    Pause = SDLK_PAUSE,
    Insert = SDLK_INSERT,
    Home = SDLK_HOME,
    PageUp = SDLK_PAGEUP,
    Delete = SDLK_DELETE,
    End = SDLK_END,
    PageDown = SDLK_PAGEDOWN,
    RightArrow = SDLK_RIGHT,
    LeftArrow = SDLK_LEFT,
    DownArrow = SDLK_DOWN,
    UpArrow = SDLK_UP,

    NumLockClear = SDLK_NUMLOCKCLEAR,
    KeypadDivide = SDLK_KP_DIVIDE,
    KeypadMultiply = SDLK_KP_MULTIPLY,
    KeypadMinus = SDLK_KP_MINUS,
    KeypadPlus = SDLK_KP_PLUS,
    KeypadEnter = SDLK_KP_ENTER,
    Keypad1 = SDLK_KP_1,
    Keypad2 = SDLK_KP_2,
    Keypad3 = SDLK_KP_3,
    Keypad4 = SDLK_KP_4,
    Keypad5 = SDLK_KP_5,
    Keypad6 = SDLK_KP_6,
    Keypad7 = SDLK_KP_7,
    Keypad8 = SDLK_KP_8,
    Keypad9 = SDLK_KP_9,
    Keypad0 = SDLK_KP_0,
    KeypadPeriod = SDLK_KP_PERIOD,

    LeftCtrl = SDLK_LCTRL,
    LeftShift = SDLK_LSHIFT,
    LeftAlt = SDLK_LALT,
    LeftGUI = SDLK_LGUI,
    RightCtrl = SDLK_RCTRL,
    RightShift = SDLK_RSHIFT,
    RightAlt = SDLK_RALT,
    RightGUI = SDLK_RGUI,
};
#endif // USE_SDL
